#! /usr/bin/env python
import sys
import csv
import os.path
import datetime


with open(sys.argv[1]) as infile:
    infile = csv.DictReader(infile)
    with open(sys.argv[2], "w") as outfile:
        outfile = csv.DictWriter(outfile, infile.fieldnames + ['weight', 'sigma'], 'ignore')
        outfile.writeheader()
        for row in infile:
            row['weight'] = row['score']
            row['sigma'] = '1.0'
            outfile.writerow(row)
