#! /usr/bin/env python

import sys
import csv
import os.path

infilenames = sys.argv[1:-1]
outfilename = sys.argv[-1]

fieldnames = set()
for infilename in infilenames:
    with open(infilename) as f:
        f = csv.DictReader(f)
        fieldnames = fieldnames.union(f.fieldnames)

with open(outfilename, "w") as outfile:
    outfile = csv.DictWriter(outfile, fieldnames, 'ignore')
    outfile.writeheader()
    for infilename in infilenames:
        with open(infilename) as f:
            f = csv.DictReader(f)
            for row in f:
                outfile.writerow(row)

