#! /usr/bin/env python

import sys
import csv
import os.path

def parseArgs(argv, *files, **args): 
    args = dict(args)
    files = list(files)
    for arg in argv:
        if arg.startswith("--"):
            arg = arg[2:]
            if '=' in arg:
                arg, value = arg.split("=", 1)
                args[arg] = value
            else:
                args[arg] = True
        else:
            files.append(arg)
    return args, files

args, files = parseArgs(sys.argv[1:],
                        timeunit=24*60*60,
                        outdir=".")

args["timeunit"] = int(args["timeunit"])

with open(files[0]) as infile:
    infile = csv.DictReader(infile)
    for row in infile:
        timebucket = int(row['timestamp']) - (int(row['timestamp']) % int(args['timeunit']))
        filename = "%s/%s.csv" % (args['outdir'], timebucket)
        is_new = not os.path.exists(filename)        
        with open(filename, "a") as outfile:
            outfile = csv.DictWriter(outfile, infile.fieldnames, 'ignore')
            if is_new: outfile.writeheader()
            outfile.writerow(row)

